- hosts: all
  name: install docker on the server
  become: true
  vars:
    docker_package: docker
    docker_compose_url: https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64
    docker_compose_path: /usr/local/bin/docker-compose

  tasks:
    - name: install docker
      package: 
        name: {{  "docker_package" }}
        state: present

    - name: install docker_compose_path
      get_url:
        url: {{  "docker_compose_url" }}
        dest: {{  "docker_compose_path" }}
        mode: '0755'

    - name: start and enable docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: start and enable "docker_compose_"
      service:
        name: docker_compose_path
        state: started
        enabled: yes

    - name: clone a git repo 
      git: 
        repo: https://github.com/Abhimanyu89403/Event-Processing-System-with-Auto-Deployment.git
        dest: /root/apps


# ansible-playbook --check playbook.yml  (dry run)
# ansible-playbook  -i inventory.ini playbook.yml

